[project]
name = "ultimate-chinese"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "brain-brew>=0.3.11",
    "pandas>=2.2.3",
    "pypinyin>=0.53.0",
]
