crowdanki_uuid: 39b9f4b2-9f7a-11ef-9d36-dd15fb18eb97
deck_config_uuid: faaf0a22-8b9d-11ef-82dd-c1456c06313e
name: Ultimate Chinese
deck_configurations:
  - __type__: DeckConfig
    crowdanki_uuid: faaf0a22-8b9d-11ef-82dd-c1456c06313e
    name: Ultimate Chinese
