crowdanki_uuid: 39b9f4b2-9f7a-11ef-9d36-dd15fb18eb97
deck_config_uuid: faaf0a22-8b9d-11ef-82dd-c1456c06313e
name: Ultimate Chinese
deck_configurations:
  - __type__: DeckConfig
    crowdanki_uuid: faaf0a22-8b9d-11ef-82dd-c1456c06313e
    name: Ultimate Chinese
    answerAction: 0
    autoplay: false
    buryInterdayLearning: false
    desiredRetention: 0.85
    dyn: false
    ignoreRevlogsBeforeDate: "1970-01-01"
    interdayLearningMix: 0
    lapse:
      delays:
        - 10.0
      leechAction: 1
      leechFails: 9999
      minInt: 1
      mult: 0.0
    maxTaken: 60
    new:
      bury: true
      delays:
        - 1.0
        - 10.0
      initialFactor: 2500
      ints:
        - 1
        - 4
        - 0
      order: 1
      perDay: 20
    newGatherPriority: 0
    newMix: 0
    newPerDayMinimum: 0
    newSortOrder: 1
    questionAction: 0
    replayq: true
    rev:
      bury: true
      ease4: 1.3
      hardFactor: 1.2
      ivlFct: 1.0
      maxIvl: 36500
      perDay: 200
    reviewOrder: 0
    waitForAudio: true
dyn: 0
extendNew: 0
extendRev: 0
