name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release Deck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest uv
        uses: astral-sh/setup-uv@v5

      - name: Create build directory
        run: mkdir -p build

      - name: Generate notes.csv from words.json
        run: uv run src/build_words.py --input res/words.json --output build/notes.csv

      - name: Generate CSS from style.scss
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: src/note_models/style.scss
          destination: build/style.css

      - name: Run brainbrew
        run: uv run brainbrew run recipes/source_to_anki.yaml

      - name: Create zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -r Ultimate_Chinese.zip build/Ultimate_Chinese

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build/Ultimate_Chinese.zip
